name: Sonar
on:
    workflow_call: # Permite que este workflow seja chamado por outro

  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      # Checkout do código
      - uses: actions/checkout@v4
      # Instalar dependências usando Yar
      - name: Install dependencies
        run: yarn
      # Rodar testes e gerar cobertura
      - name: Test and coverage
        run: yarn jest --coverage
      # Rodar a análise no SonarQube
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} # Token do GitHub (para acessar a API do GitHub)
          SONAR_TOKEN: ${{secrets.SONARCLOUD_TOKEN}} # Token do SonarCloud (para autenticação na plataforma)
